/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// A background query the calling user currently has available to them
    /// </summary>
    [DataContract(Name = "BackgroundQueryListItem")]
    public partial class BackgroundQueryListItem : IEquatable<BackgroundQueryListItem>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public BackgroundQueryState? State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="BackgroundQueryListItem" /> class.
        /// </summary>
        /// <param name="executionId">ExecutionId of the query.</param>
        /// <param name="query">The LuminesceSql of the original request.</param>
        /// <param name="queryName">The QueryName given in the original request.</param>
        /// <param name="state">state.</param>
        /// <param name="when">When the state of this query (and so its data) was last updated (UTC).</param>
        /// <param name="expiresAt">When the query (and its data) may be removed (UTC).</param>
        public BackgroundQueryListItem(string executionId = default(string), string query = default(string), string queryName = default(string), BackgroundQueryState ?state = default(BackgroundQueryState?), DateTimeOffset when = default(DateTimeOffset), DateTimeOffset expiresAt = default(DateTimeOffset))
        {
            this.ExecutionId = executionId;
            this.Query = query;
            this.QueryName = queryName;
            this.State = state;
            this.When = when;
            this.ExpiresAt = expiresAt;
        }

        /// <summary>
        /// ExecutionId of the query
        /// </summary>
        /// <value>ExecutionId of the query</value>
        [DataMember(Name = "executionId", EmitDefaultValue = true)]
        public string ExecutionId { get; set; }

        /// <summary>
        /// The LuminesceSql of the original request
        /// </summary>
        /// <value>The LuminesceSql of the original request</value>
        [DataMember(Name = "query", EmitDefaultValue = true)]
        public string Query { get; set; }

        /// <summary>
        /// The QueryName given in the original request
        /// </summary>
        /// <value>The QueryName given in the original request</value>
        [DataMember(Name = "queryName", EmitDefaultValue = true)]
        public string QueryName { get; set; }

        /// <summary>
        /// When the state of this query (and so its data) was last updated (UTC)
        /// </summary>
        /// <value>When the state of this query (and so its data) was last updated (UTC)</value>
        [DataMember(Name = "when", EmitDefaultValue = false)]
        public DateTimeOffset When { get; set; }

        /// <summary>
        /// When the query (and its data) may be removed (UTC)
        /// </summary>
        /// <value>When the query (and its data) may be removed (UTC)</value>
        [DataMember(Name = "expiresAt", EmitDefaultValue = false)]
        public DateTimeOffset ExpiresAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BackgroundQueryListItem {\n");
            sb.Append("  ExecutionId: ").Append(ExecutionId).Append("\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  QueryName: ").Append(QueryName).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  When: ").Append(When).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BackgroundQueryListItem);
        }

        /// <summary>
        /// Returns true if BackgroundQueryListItem instances are equal
        /// </summary>
        /// <param name="input">Instance of BackgroundQueryListItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BackgroundQueryListItem input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ExecutionId == input.ExecutionId ||
                    (this.ExecutionId != null &&
                    this.ExecutionId.Equals(input.ExecutionId))
                ) && 
                (
                    this.Query == input.Query ||
                    (this.Query != null &&
                    this.Query.Equals(input.Query))
                ) && 
                (
                    this.QueryName == input.QueryName ||
                    (this.QueryName != null &&
                    this.QueryName.Equals(input.QueryName))
                ) && 
                (
                    this.State == input.State ||
                    this.State.Equals(input.State)
                ) && 
                (
                    this.When == input.When ||
                    (this.When != null &&
                    this.When.Equals(input.When))
                ) && 
                (
                    this.ExpiresAt == input.ExpiresAt ||
                    (this.ExpiresAt != null &&
                    this.ExpiresAt.Equals(input.ExpiresAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ExecutionId != null)
                {
                    hashCode = (hashCode * 59) + this.ExecutionId.GetHashCode();
                }
                if (this.Query != null)
                {
                    hashCode = (hashCode * 59) + this.Query.GetHashCode();
                }
                if (this.QueryName != null)
                {
                    hashCode = (hashCode * 59) + this.QueryName.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.State.GetHashCode();
                if (this.When != null)
                {
                    hashCode = (hashCode * 59) + this.When.GetHashCode();
                }
                if (this.ExpiresAt != null)
                {
                    hashCode = (hashCode * 59) + this.ExpiresAt.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
