/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// Which System(s) have been updated with a given request
    /// </summary>
    /// <value>Which System(s) have been updated with a given request</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CertificateStatus
    {
        /// <summary>
        /// Enum None for value: None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 1,

        /// <summary>
        /// Enum WebApiPersistence for value: WebApiPersistence
        /// </summary>
        [EnumMember(Value = "WebApiPersistence")]
        WebApiPersistence = 2,

        /// <summary>
        /// Enum Vault for value: Vault
        /// </summary>
        [EnumMember(Value = "Vault")]
        Vault = 3,

        /// <summary>
        /// Enum WebApiPersistenceVault for value: WebApiPersistenceVault
        /// </summary>
        [EnumMember(Value = "WebApiPersistenceVault")]
        WebApiPersistenceVault = 4,

        /// <summary>
        /// Enum Rabbit for value: Rabbit
        /// </summary>
        [EnumMember(Value = "Rabbit")]
        Rabbit = 5,

        /// <summary>
        /// Enum WebApiPersistenceRabbit for value: WebApiPersistenceRabbit
        /// </summary>
        [EnumMember(Value = "WebApiPersistenceRabbit")]
        WebApiPersistenceRabbit = 6,

        /// <summary>
        /// Enum VaultRabbit for value: VaultRabbit
        /// </summary>
        [EnumMember(Value = "VaultRabbit")]
        VaultRabbit = 7,

        /// <summary>
        /// Enum WebApiPersistenceVaultRabbit for value: WebApiPersistenceVaultRabbit
        /// </summary>
        [EnumMember(Value = "WebApiPersistenceVaultRabbit")]
        WebApiPersistenceVaultRabbit = 8,

        /// <summary>
        /// Enum ConfigStore for value: ConfigStore
        /// </summary>
        [EnumMember(Value = "ConfigStore")]
        ConfigStore = 9,

        /// <summary>
        /// Enum WebApiPersistenceConfigStore for value: WebApiPersistenceConfigStore
        /// </summary>
        [EnumMember(Value = "WebApiPersistenceConfigStore")]
        WebApiPersistenceConfigStore = 10,

        /// <summary>
        /// Enum VaultConfigStore for value: VaultConfigStore
        /// </summary>
        [EnumMember(Value = "VaultConfigStore")]
        VaultConfigStore = 11,

        /// <summary>
        /// Enum WebApiPersistenceVaultConfigStore for value: WebApiPersistenceVaultConfigStore
        /// </summary>
        [EnumMember(Value = "WebApiPersistenceVaultConfigStore")]
        WebApiPersistenceVaultConfigStore = 12,

        /// <summary>
        /// Enum RabbitConfigStore for value: RabbitConfigStore
        /// </summary>
        [EnumMember(Value = "RabbitConfigStore")]
        RabbitConfigStore = 13,

        /// <summary>
        /// Enum WebApiPersistenceRabbitConfigStore for value: WebApiPersistenceRabbitConfigStore
        /// </summary>
        [EnumMember(Value = "WebApiPersistenceRabbitConfigStore")]
        WebApiPersistenceRabbitConfigStore = 14,

        /// <summary>
        /// Enum VaultRabbitConfigStore for value: VaultRabbitConfigStore
        /// </summary>
        [EnumMember(Value = "VaultRabbitConfigStore")]
        VaultRabbitConfigStore = 15,

        /// <summary>
        /// Enum AllSystems for value: AllSystems
        /// </summary>
        [EnumMember(Value = "AllSystems")]
        AllSystems = 16
    }

}
