/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// Dashboard type (input or output)
    /// </summary>
    /// <value>Dashboard type (input or output)</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DashboardType
    {
        /// <summary>
        /// Enum Input for value: input
        /// </summary>
        [EnumMember(Value = "input")]
        Input = 1,

        /// <summary>
        /// Enum Output for value: output
        /// </summary>
        [EnumMember(Value = "output")]
        Output = 2
    }

}
