/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// The types of Exporting capable of being delivered by the WebAPI. Similar but not identical to &lt;seealso cref&#x3D;\&quot;T:Finbourne.Honeycomb.Api.Hosting.Exporting.OutputType\&quot; /&gt;
    /// </summary>
    /// <value>The types of Exporting capable of being delivered by the WebAPI. Similar but not identical to &lt;seealso cref&#x3D;\&quot;T:Finbourne.Honeycomb.Api.Hosting.Exporting.OutputType\&quot; /&gt;</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ExportType
    {
        /// <summary>
        /// Enum Csv for value: csv
        /// </summary>
        [EnumMember(Value = "csv")]
        Csv = 1,

        /// <summary>
        /// Enum Pipe for value: pipe
        /// </summary>
        [EnumMember(Value = "pipe")]
        Pipe = 2,

        /// <summary>
        /// Enum Excel for value: excel
        /// </summary>
        [EnumMember(Value = "excel")]
        Excel = 3,

        /// <summary>
        /// Enum Json for value: json
        /// </summary>
        [EnumMember(Value = "json")]
        Json = 4,

        /// <summary>
        /// Enum JsonProper for value: jsonProper
        /// </summary>
        [EnumMember(Value = "jsonProper")]
        JsonProper = 5,

        /// <summary>
        /// Enum Xml for value: xml
        /// </summary>
        [EnumMember(Value = "xml")]
        Xml = 6,

        /// <summary>
        /// Enum Parquet for value: parquet
        /// </summary>
        [EnumMember(Value = "parquet")]
        Parquet = 7,

        /// <summary>
        /// Enum Sqlite for value: sqlite
        /// </summary>
        [EnumMember(Value = "sqlite")]
        Sqlite = 8,

        /// <summary>
        /// Enum TableInternal for value: TableInternal
        /// </summary>
        [EnumMember(Value = "TableInternal")]
        TableInternal = 9,

        /// <summary>
        /// Enum JsonProperWithLineage for value: jsonProperWithLineage
        /// </summary>
        [EnumMember(Value = "jsonProperWithLineage")]
        JsonProperWithLineage = 10,

        /// <summary>
        /// Enum Pdf for value: pdf
        /// </summary>
        [EnumMember(Value = "pdf")]
        Pdf = 11
    }

}
