/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// Lineage
    /// </summary>
    [DataContract(Name = "Lineage")]
    public partial class Lineage : IEquatable<Lineage>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Lineage" /> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="subtype">subtype.</param>
        /// <param name="alias">alias.</param>
        /// <param name="columnTitleTooltip">columnTitleTooltip.</param>
        /// <param name="explainTitle">explainTitle.</param>
        /// <param name="explainTooltip">explainTooltip.</param>
        /// <param name="fullFormula">fullFormula.</param>
        /// <param name="documentationAsHtml">documentationAsHtml.</param>
        /// <param name="documentationAsMarkDown">documentationAsMarkDown.</param>
        /// <param name="children">children.</param>
        public Lineage(string type = default(string), string subtype = default(string), string alias = default(string), string columnTitleTooltip = default(string), string explainTitle = default(string), string explainTooltip = default(string), string fullFormula = default(string), string documentationAsHtml = default(string), string documentationAsMarkDown = default(string), List<Lineage> children = default(List<Lineage>))
        {
            this.Type = type;
            this.Subtype = subtype;
            this.Alias = alias;
            this.ColumnTitleTooltip = columnTitleTooltip;
            this.ExplainTitle = explainTitle;
            this.ExplainTooltip = explainTooltip;
            this.FullFormula = fullFormula;
            this.DocumentationAsHtml = documentationAsHtml;
            this.DocumentationAsMarkDown = documentationAsMarkDown;
            this.Children = children;
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Subtype
        /// </summary>
        [DataMember(Name = "subtype", EmitDefaultValue = true)]
        public string Subtype { get; set; }

        /// <summary>
        /// Gets or Sets Alias
        /// </summary>
        [DataMember(Name = "alias", EmitDefaultValue = true)]
        public string Alias { get; set; }

        /// <summary>
        /// Gets or Sets ColumnTitleTooltip
        /// </summary>
        [DataMember(Name = "columnTitleTooltip", EmitDefaultValue = true)]
        public string ColumnTitleTooltip { get; set; }

        /// <summary>
        /// Gets or Sets ExplainTitle
        /// </summary>
        [DataMember(Name = "explainTitle", EmitDefaultValue = true)]
        public string ExplainTitle { get; set; }

        /// <summary>
        /// Gets or Sets ExplainTooltip
        /// </summary>
        [DataMember(Name = "explainTooltip", EmitDefaultValue = true)]
        public string ExplainTooltip { get; set; }

        /// <summary>
        /// Gets or Sets FullFormula
        /// </summary>
        [DataMember(Name = "fullFormula", EmitDefaultValue = true)]
        public string FullFormula { get; set; }

        /// <summary>
        /// Gets or Sets DocumentationAsHtml
        /// </summary>
        [DataMember(Name = "documentationAsHtml", EmitDefaultValue = true)]
        public string DocumentationAsHtml { get; set; }

        /// <summary>
        /// Gets or Sets DocumentationAsMarkDown
        /// </summary>
        [DataMember(Name = "documentationAsMarkDown", EmitDefaultValue = true)]
        public string DocumentationAsMarkDown { get; set; }

        /// <summary>
        /// Gets or Sets Children
        /// </summary>
        [DataMember(Name = "children", EmitDefaultValue = true)]
        public List<Lineage> Children { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Lineage {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Subtype: ").Append(Subtype).Append("\n");
            sb.Append("  Alias: ").Append(Alias).Append("\n");
            sb.Append("  ColumnTitleTooltip: ").Append(ColumnTitleTooltip).Append("\n");
            sb.Append("  ExplainTitle: ").Append(ExplainTitle).Append("\n");
            sb.Append("  ExplainTooltip: ").Append(ExplainTooltip).Append("\n");
            sb.Append("  FullFormula: ").Append(FullFormula).Append("\n");
            sb.Append("  DocumentationAsHtml: ").Append(DocumentationAsHtml).Append("\n");
            sb.Append("  DocumentationAsMarkDown: ").Append(DocumentationAsMarkDown).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Lineage);
        }

        /// <summary>
        /// Returns true if Lineage instances are equal
        /// </summary>
        /// <param name="input">Instance of Lineage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Lineage input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Subtype == input.Subtype ||
                    (this.Subtype != null &&
                    this.Subtype.Equals(input.Subtype))
                ) && 
                (
                    this.Alias == input.Alias ||
                    (this.Alias != null &&
                    this.Alias.Equals(input.Alias))
                ) && 
                (
                    this.ColumnTitleTooltip == input.ColumnTitleTooltip ||
                    (this.ColumnTitleTooltip != null &&
                    this.ColumnTitleTooltip.Equals(input.ColumnTitleTooltip))
                ) && 
                (
                    this.ExplainTitle == input.ExplainTitle ||
                    (this.ExplainTitle != null &&
                    this.ExplainTitle.Equals(input.ExplainTitle))
                ) && 
                (
                    this.ExplainTooltip == input.ExplainTooltip ||
                    (this.ExplainTooltip != null &&
                    this.ExplainTooltip.Equals(input.ExplainTooltip))
                ) && 
                (
                    this.FullFormula == input.FullFormula ||
                    (this.FullFormula != null &&
                    this.FullFormula.Equals(input.FullFormula))
                ) && 
                (
                    this.DocumentationAsHtml == input.DocumentationAsHtml ||
                    (this.DocumentationAsHtml != null &&
                    this.DocumentationAsHtml.Equals(input.DocumentationAsHtml))
                ) && 
                (
                    this.DocumentationAsMarkDown == input.DocumentationAsMarkDown ||
                    (this.DocumentationAsMarkDown != null &&
                    this.DocumentationAsMarkDown.Equals(input.DocumentationAsMarkDown))
                ) && 
                (
                    this.Children == input.Children ||
                    this.Children != null &&
                    input.Children != null &&
                    this.Children.SequenceEqual(input.Children)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                if (this.Subtype != null)
                {
                    hashCode = (hashCode * 59) + this.Subtype.GetHashCode();
                }
                if (this.Alias != null)
                {
                    hashCode = (hashCode * 59) + this.Alias.GetHashCode();
                }
                if (this.ColumnTitleTooltip != null)
                {
                    hashCode = (hashCode * 59) + this.ColumnTitleTooltip.GetHashCode();
                }
                if (this.ExplainTitle != null)
                {
                    hashCode = (hashCode * 59) + this.ExplainTitle.GetHashCode();
                }
                if (this.ExplainTooltip != null)
                {
                    hashCode = (hashCode * 59) + this.ExplainTooltip.GetHashCode();
                }
                if (this.FullFormula != null)
                {
                    hashCode = (hashCode * 59) + this.FullFormula.GetHashCode();
                }
                if (this.DocumentationAsHtml != null)
                {
                    hashCode = (hashCode * 59) + this.DocumentationAsHtml.GetHashCode();
                }
                if (this.DocumentationAsMarkDown != null)
                {
                    hashCode = (hashCode * 59) + this.DocumentationAsMarkDown.GetHashCode();
                }
                if (this.Children != null)
                {
                    hashCode = (hashCode * 59) + this.Children.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
