/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// Defines LineageColumnIcon
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LineageColumnIcon
    {
        /// <summary>
        /// Enum None for value: None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 1,

        /// <summary>
        /// Enum Calculation for value: Calculation
        /// </summary>
        [EnumMember(Value = "Calculation")]
        Calculation = 2,

        /// <summary>
        /// Enum Aggregation for value: Aggregation
        /// </summary>
        [EnumMember(Value = "Aggregation")]
        Aggregation = 3,

        /// <summary>
        /// Enum DerivedProperty for value: DerivedProperty
        /// </summary>
        [EnumMember(Value = "DerivedProperty")]
        DerivedProperty = 4
    }

}
