/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// Versions of the Query Designer as evolving over time. Generally only the two largest values will be supported at any one time.
    /// </summary>
    /// <value>Versions of the Query Designer as evolving over time. Generally only the two largest values will be supported at any one time.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum QueryDesignerVersion
    {
        /// <summary>
        /// Enum Original for value: Original
        /// </summary>
        [EnumMember(Value = "Original")]
        Original = 1,

        /// <summary>
        /// Enum JoinsAndIsNull for value: JoinsAndIsNull
        /// </summary>
        [EnumMember(Value = "JoinsAndIsNull")]
        JoinsAndIsNull = 2
    }

}
