/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// The file type of a source
    /// </summary>
    /// <value>The file type of a source</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SourceType
    {
        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown,

        /// <summary>
        /// Enum Csv for value: Csv
        /// </summary>
        [EnumMember(Value = "Csv")]
        Csv,

        /// <summary>
        /// Enum Excel for value: Excel
        /// </summary>
        [EnumMember(Value = "Excel")]
        Excel,

        /// <summary>
        /// Enum SqLite for value: SqLite
        /// </summary>
        [EnumMember(Value = "SqLite")]
        SqLite,

        /// <summary>
        /// Enum Xml for value: Xml
        /// </summary>
        [EnumMember(Value = "Xml")]
        Xml,

        /// <summary>
        /// Enum Parquet for value: Parquet
        /// </summary>
        [EnumMember(Value = "Parquet")]
        Parquet,

        /// <summary>
        /// Enum RawText for value: RawText
        /// </summary>
        [EnumMember(Value = "RawText")]
        RawText
    }

}
