/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// TableLineage
    /// </summary>
    [DataContract(Name = "TableLineage")]
    public partial class TableLineage : IEquatable<TableLineage>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TableLineage" /> class.
        /// </summary>
        /// <param name="columnLineage">columnLineage.</param>
        /// <param name="wholeTableLineage">wholeTableLineage.</param>
        /// <param name="failureReason">failureReason.</param>
        public TableLineage(List<Lineage> columnLineage = default(List<Lineage>), Lineage wholeTableLineage = default(Lineage), string failureReason = default(string))
        {
            this.ColumnLineage = columnLineage;
            this.WholeTableLineage = wholeTableLineage;
            this.FailureReason = failureReason;
        }

        /// <summary>
        /// Gets or Sets ColumnLineage
        /// </summary>
        [DataMember(Name = "columnLineage", EmitDefaultValue = true)]
        public List<Lineage> ColumnLineage { get; set; }

        /// <summary>
        /// Gets or Sets WholeTableLineage
        /// </summary>
        [DataMember(Name = "wholeTableLineage", EmitDefaultValue = false)]
        public Lineage WholeTableLineage { get; set; }

        /// <summary>
        /// Gets or Sets FailureReason
        /// </summary>
        [DataMember(Name = "failureReason", EmitDefaultValue = true)]
        public string FailureReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TableLineage {\n");
            sb.Append("  ColumnLineage: ").Append(ColumnLineage).Append("\n");
            sb.Append("  WholeTableLineage: ").Append(WholeTableLineage).Append("\n");
            sb.Append("  FailureReason: ").Append(FailureReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TableLineage);
        }

        /// <summary>
        /// Returns true if TableLineage instances are equal
        /// </summary>
        /// <param name="input">Instance of TableLineage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TableLineage input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ColumnLineage == input.ColumnLineage ||
                    this.ColumnLineage != null &&
                    input.ColumnLineage != null &&
                    this.ColumnLineage.SequenceEqual(input.ColumnLineage)
                ) && 
                (
                    this.WholeTableLineage == input.WholeTableLineage ||
                    (this.WholeTableLineage != null &&
                    this.WholeTableLineage.Equals(input.WholeTableLineage))
                ) && 
                (
                    this.FailureReason == input.FailureReason ||
                    (this.FailureReason != null &&
                    this.FailureReason.Equals(input.FailureReason))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ColumnLineage != null)
                {
                    hashCode = (hashCode * 59) + this.ColumnLineage.GetHashCode();
                }
                if (this.WholeTableLineage != null)
                {
                    hashCode = (hashCode * 59) + this.WholeTableLineage.GetHashCode();
                }
                if (this.FailureReason != null)
                {
                    hashCode = (hashCode * 59) + this.FailureReason.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
