/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// Representation of the table metadata
    /// </summary>
    [DataContract(Name = "TableMeta")]
    public partial class TableMeta : IEquatable<TableMeta>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TableMeta" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TableMeta() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TableMeta" /> class.
        /// </summary>
        /// <param name="tableId">A unique identifier for the table (required).</param>
        public TableMeta(string tableId = default(string))
        {
            // to ensure "tableId" is required (not null)
            if (tableId == null)
            {
                throw new ArgumentNullException("tableId is a required property for TableMeta and cannot be null");
            }
            this.TableId = tableId;
        }

        /// <summary>
        /// A unique identifier for the table
        /// </summary>
        /// <value>A unique identifier for the table</value>
        [DataMember(Name = "tableId", IsRequired = true, EmitDefaultValue = true)]
        public string TableId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TableMeta {\n");
            sb.Append("  TableId: ").Append(TableId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TableMeta);
        }

        /// <summary>
        /// Returns true if TableMeta instances are equal
        /// </summary>
        /// <param name="input">Instance of TableMeta to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TableMeta input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TableId == input.TableId ||
                    (this.TableId != null &&
                    this.TableId.Equals(input.TableId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TableId != null)
                {
                    hashCode = (hashCode * 59) + this.TableId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TableId (string) minLength
            if (this.TableId != null && this.TableId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TableId, length must be greater than 1.", new [] { "TableId" });
            }

            yield break;
        }
    }
}
