/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Luminesce.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Luminesce.Sdk.Model
{
    /// <summary>
    /// ViewItem
    /// </summary>
    [DataContract(Name = "ViewItem")]
    public partial class ViewItem : IEquatable<ViewItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ViewItem" /> class.
        /// </summary>
        /// <param name="name">The name of the view.</param>
        /// <param name="domain">The domain the view applies to.</param>
        /// <param name="filePath">The full file path in the HcFs.</param>
        /// <param name="fileContent">The full file content in the HcFs. This will be needed for Upserting the view to a different domain / for use in fbn-config..</param>
        /// <param name="lastUpdatedExecutionId">The last ExecutionId, needed to get the creating Sql out of the logs.</param>
        /// <param name="lastUpdatedAt">The last updated at time, needed to get the creating Sql out of the logs.</param>
        /// <param name="lastUpdatedBy">The last updated by this user.</param>
        /// <param name="createdByUserId">Originally created by this user.</param>
        public ViewItem(string name = default(string), string domain = default(string), string filePath = default(string), string fileContent = default(string), Guid? lastUpdatedExecutionId = default(Guid?), DateTimeOffset? lastUpdatedAt = default(DateTimeOffset?), string lastUpdatedBy = default(string), string createdByUserId = default(string))
        {
            this.Name = name;
            this.Domain = domain;
            this.FilePath = filePath;
            this.FileContent = fileContent;
            this.LastUpdatedExecutionId = lastUpdatedExecutionId;
            this.LastUpdatedAt = lastUpdatedAt;
            this.LastUpdatedBy = lastUpdatedBy;
            this.CreatedByUserId = createdByUserId;
        }

        /// <summary>
        /// The name of the view
        /// </summary>
        /// <value>The name of the view</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The domain the view applies to
        /// </summary>
        /// <value>The domain the view applies to</value>
        [DataMember(Name = "domain", EmitDefaultValue = true)]
        public string Domain { get; set; }

        /// <summary>
        /// The full file path in the HcFs
        /// </summary>
        /// <value>The full file path in the HcFs</value>
        [DataMember(Name = "filePath", EmitDefaultValue = true)]
        public string FilePath { get; set; }

        /// <summary>
        /// The full file content in the HcFs. This will be needed for Upserting the view to a different domain / for use in fbn-config.
        /// </summary>
        /// <value>The full file content in the HcFs. This will be needed for Upserting the view to a different domain / for use in fbn-config.</value>
        [DataMember(Name = "fileContent", EmitDefaultValue = true)]
        public string FileContent { get; set; }

        /// <summary>
        /// The last ExecutionId, needed to get the creating Sql out of the logs
        /// </summary>
        /// <value>The last ExecutionId, needed to get the creating Sql out of the logs</value>
        [DataMember(Name = "lastUpdatedExecutionId", EmitDefaultValue = true)]
        public Guid? LastUpdatedExecutionId { get; set; }

        /// <summary>
        /// The last updated at time, needed to get the creating Sql out of the logs
        /// </summary>
        /// <value>The last updated at time, needed to get the creating Sql out of the logs</value>
        [DataMember(Name = "lastUpdatedAt", EmitDefaultValue = true)]
        public DateTimeOffset? LastUpdatedAt { get; set; }

        /// <summary>
        /// The last updated by this user
        /// </summary>
        /// <value>The last updated by this user</value>
        [DataMember(Name = "lastUpdatedBy", EmitDefaultValue = true)]
        public string LastUpdatedBy { get; set; }

        /// <summary>
        /// Originally created by this user
        /// </summary>
        /// <value>Originally created by this user</value>
        [DataMember(Name = "createdByUserId", EmitDefaultValue = true)]
        public string CreatedByUserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ViewItem {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  FilePath: ").Append(FilePath).Append("\n");
            sb.Append("  FileContent: ").Append(FileContent).Append("\n");
            sb.Append("  LastUpdatedExecutionId: ").Append(LastUpdatedExecutionId).Append("\n");
            sb.Append("  LastUpdatedAt: ").Append(LastUpdatedAt).Append("\n");
            sb.Append("  LastUpdatedBy: ").Append(LastUpdatedBy).Append("\n");
            sb.Append("  CreatedByUserId: ").Append(CreatedByUserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ViewItem);
        }

        /// <summary>
        /// Returns true if ViewItem instances are equal
        /// </summary>
        /// <param name="input">Instance of ViewItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ViewItem input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Domain == input.Domain ||
                    (this.Domain != null &&
                    this.Domain.Equals(input.Domain))
                ) && 
                (
                    this.FilePath == input.FilePath ||
                    (this.FilePath != null &&
                    this.FilePath.Equals(input.FilePath))
                ) && 
                (
                    this.FileContent == input.FileContent ||
                    (this.FileContent != null &&
                    this.FileContent.Equals(input.FileContent))
                ) && 
                (
                    this.LastUpdatedExecutionId == input.LastUpdatedExecutionId ||
                    (this.LastUpdatedExecutionId != null &&
                    this.LastUpdatedExecutionId.Equals(input.LastUpdatedExecutionId))
                ) && 
                (
                    this.LastUpdatedAt == input.LastUpdatedAt ||
                    (this.LastUpdatedAt != null &&
                    this.LastUpdatedAt.Equals(input.LastUpdatedAt))
                ) && 
                (
                    this.LastUpdatedBy == input.LastUpdatedBy ||
                    (this.LastUpdatedBy != null &&
                    this.LastUpdatedBy.Equals(input.LastUpdatedBy))
                ) && 
                (
                    this.CreatedByUserId == input.CreatedByUserId ||
                    (this.CreatedByUserId != null &&
                    this.CreatedByUserId.Equals(input.CreatedByUserId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Domain != null)
                {
                    hashCode = (hashCode * 59) + this.Domain.GetHashCode();
                }
                if (this.FilePath != null)
                {
                    hashCode = (hashCode * 59) + this.FilePath.GetHashCode();
                }
                if (this.FileContent != null)
                {
                    hashCode = (hashCode * 59) + this.FileContent.GetHashCode();
                }
                if (this.LastUpdatedExecutionId != null)
                {
                    hashCode = (hashCode * 59) + this.LastUpdatedExecutionId.GetHashCode();
                }
                if (this.LastUpdatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.LastUpdatedAt.GetHashCode();
                }
                if (this.LastUpdatedBy != null)
                {
                    hashCode = (hashCode * 59) + this.LastUpdatedBy.GetHashCode();
                }
                if (this.CreatedByUserId != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedByUserId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
